import java.util.ArrayList;

public class Brain {
    /** The Neural Net of a cell
    * TO BE IMPLEMENTED
     */
    int placeholder;
    Cell holderCell;
    /**
    * @param inputGenome stores the input genome
    * 
    * Should initialize a neural net with connections/tendencies based on the genome
     */
    public Brain(Cell inputCell, ArrayList<String> inputGenome) {
        
    }
}